# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
## Use a package of configuration called an orb.
#orbs:
#  # Declare a dependency on the welcome-orb
#  welcome: circleci/welcome-orb@0.4.1
## Orchestrate or schedule a set of jobs
#workflows:
#  # Name the workflow "welcome"
#  welcome:
#    # Run the welcome/run job in its own container
#    jobs:
#      - welcome/run
jobs:
  build:
    docker:
      - image: circleci/python:stretch
    steps:
      - checkout
#      - restore_cache:
#        key: pip-v1-{{ arch }}-{{ checksum "VoidFinder/requirements.txt" }}
#      - run:
#        name: "Install VoidFinder dependencies"
#        working_directory: VoidFinder
#        command: |
#          pip install -r requirements.txt --user --progress-bar off
#      - save_cache:
#        key: pip-v1-{{ arch }}-{{ checksum "VoidFinder/requirements.txt" }}
#        paths:
#          - /home/circleci/.local/lib/python3.8/site-packages
      - run:
        name: Install VAST-VoidFinder
        working_directory: VoidFinder
        command: python setup.py install --user
