version: 2.0

jobs:
  build:
    working_directory: ~/VAST/VoidFinder
    docker:
      -image: circleci/python:stretch
    steps:
      - checkout
      - restore_cache:
        key: pip-v1-{{ arch }}-{{ checksum "requirements.txt" }}
      - run:
        command: |
          pip install -r requirements.txt --user --progress-bar off
      - save_cache:
        key: pip-v1-{{ arch }}-{{ checksum "requirements.txt" }}
        paths:
          - ".venv"
          - "/usr/local/bin"
          - "/usr/local/lib/python3.6/site-packages"
