version: 2.0

jobs:
  "VoidFinder":
    docker:
      -image: circleci/python:stretch
    working_directory: VoidFinder
    steps:
      - checkout
      - run:
        name: Install VF Dependencies
        command: pip install -r requirements.txt --user --progress-bar off
      - run:
        name: Install VoidFinder
        command: python setup.py install --user

workflows:
  version: 2
  build:
    jobs:
      - "VoidFinder"
