# Trusted publishing on PyPI.
# See https://docs.pypi.org/trusted-publishers/
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: pypi
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    steps:
      # retrieve your distributions here
#      - name: Publish package distributions to PyPI
#        uses: pypa/gh-action-pypi-publish@release/v1
			- name: Publish package distributions to TestPyPI
				uses: pypa/gh-action-pypi-publish@release/v1
				with:
					repository-url: https://test.pypi.org/legacy/

    # Only publish tags rather than releases.
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
